baseURL: https://smileisak.com/
languageCode: en-us
title: "@smileisak"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: UA-171661420-2

# Enable Disqus forum
disqusShortname: smileisak

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # copyright
  copyright: © 2020 Copyright.

  # background image of the landing page
  background: "/assets/images/wallpaper.jpg"

  # GitHub repo URL of your site
  gitRepo: https://github.com/hossainemruz/toha-example-site

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  customMenus: []


  # some information about you
  author:
    name: "Ismail KABOUBI"
    image: "/assets/images/avatar.png"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "ikaboubi@gmail.com"
      phone: "+33 6 63 01 40 09"
    # a summary of what you do
    summary:
    - I am a Software Reliability Engineer
    - I work with Python And Go
    - I love to work with some fun projects